import random

class MissionEngine:
    """Gestiona la carga y selección de misiones matemáticas con tema de Roblox."""
    def __init__(self):
        self.missions = [
            {"id": 1, "theme": "Roblox", "text": "Estás construyendo una pared con 40 bloques. Si cada fila usa 8 bloques, ¿cuántas filas podrás construir?", "answer": "5", "reward": "oof_sound", "operation_type": "División"},
            {"id": 2, "theme": "Roblox", "text": "Ganas 15 Robux por pasar un nivel y tu amigo te da 10 más. ¿Cuántos Robux tienes ahora?", "answer": "25", "reward": "oof_sound", "operation_type": "Suma"},
            {"id": 3, "theme": "Roblox", "text": "Estás en un 'obby' (parkour) con 50 plataformas. Ya has saltado 32. ¿Cuántas plataformas te faltan para llegar al final?", "answer": "18", "reward": "oof_sound", "operation_type": "Resta"},
            {"id": 4, "theme": "Roblox", "text": "En 'Adopt Me!', quieres comprar una mascota que cuesta 600 bucks. Si tienes 450, ¿cuántos más necesitas conseguir?", "answer": "150", "reward": "oof_sound", "operation_type": "Resta"},
            {"id": 5, "theme": "Roblox", "text": "Tu inventario tiene 3 espadas que hacen 10 de daño cada una. ¿Cuánto daño total hacen las tres juntas?", "answer": "30", "reward": "oof_sound", "operation_type": "Multiplicación"},
            {"id": 6, "theme": "Roblox", "text": "Una poción de velocidad cuesta 50 Robux. Si quieres comprar una para ti y para tus 3 amigos, ¿cuántos Robux necesitas?", "answer": "200", "reward": "oof_sound", "operation_type": "Multiplicación"},
            {"id": 7, "theme": "Roblox", "text": "En 'Bloxburg', una pizza cuesta 24 dólares. Si pagas con un billete de 50, ¿cuánto cambio te deben dar?", "answer": "26", "reward": "oof_sound", "operation_type": "Resta"},
            {"id": 8, "theme": "Roblox", "text": "Si un sombrero cuesta 75 Robux y compras 2, ¿cuántos Robux gastas?", "answer": "150", "reward": "oof_sound", "operation_type": "Multiplicación"},
            {"id": 9, "theme": "Roblox", "text": "En un juego tienes 120 monedas. Compras una espada por 85. ¿Cuántas monedas te quedan?", "answer": "35", "reward": "oof_sound", "operation_type": "Resta"},
            {"id": 10, "theme": "Roblox", "text": "Si ganas 25 Robux cada vez que completas una misión y completas 4, ¿cuántos Robux ganas?", "answer": "100", "reward": "oof_sound", "operation_type": "Multiplicación"},
            {"id": 11, "theme": "Roblox", "text": "Un cofre tiene 60 gemas y las compartes con 5 amigos. ¿Cuántas gemas recibe cada uno?", "answer": "12", "reward": "oof_sound", "operation_type": "División"},
            {"id": 12, "theme": "Roblox", "text": "En un obby hay 80 obstáculos. Ya pasaste 65. ¿Cuántos faltan?", "answer": "15", "reward": "oof_sound", "operation_type": "Resta"},
            {"id": 13, "theme": "Roblox", "text": "Un accesorio cuesta 45 Robux y tienes 90. ¿Cuántos accesorios puedes comprar?", "answer": "2", "reward": "oof_sound", "operation_type": "División"},
            {"id": 14, "theme": "Roblox", "text": "Si recolectas 12 bloques cada minuto, ¿cuántos bloques tendrás en 6 minutos?", "answer": "72", "reward": "oof_sound", "operation_type": "Multiplicación"},
            {"id": 15, "theme": "Roblox", "text": "Tu mascota necesita 250 bucks para una poción. Si ya tienes 175, ¿cuánto falta?", "answer": "75", "reward": "oof_sound", "operation_type": "Resta"},
            {"id": 16, "theme": "Roblox", "text": "Si un pase de juego cuesta 400 Robux y ya tienes 150, ¿cuántos más necesitas?", "answer": "250", "reward": "oof_sound", "operation_type": "Resta"},
            {"id": 17, "theme": "Roblox", "text": "Recolectas 5 gemas por nivel. ¿Cuántas gemas tendrás tras jugar 9 niveles?", "answer": "45", "reward": "oof_sound", "operation_type": "Multiplicación"},
            {"id": 18, "theme": "Roblox", "text": "En un servidor hay 18 jugadores. Si 7 se van, ¿cuántos quedan?", "answer": "11", "reward": "oof_sound", "operation_type": "Resta"},
            {"id": 19, "theme": "Roblox", "text": "Construyes una torre con 120 bloques y quieres 10 pisos iguales. ¿Cuántos bloques tendrá cada piso?", "answer": "12", "reward": "oof_sound", "operation_type": "División"},
            {"id": 20, "theme": "Roblox", "text": "Compras 3 mascotas y cada una cuesta 150 bucks. ¿Cuánto gastas en total?", "answer": "450", "reward": "oof_sound", "operation_type": "Multiplicación"},
            {"id": 21, "theme": "Roblox", "text": "Si ganas 200 Robux y luego gastas 125 en un accesorio, ¿cuántos Robux te quedan?", "answer": "75", "reward": "oof_sound", "operation_type": "Resta"},
            {"id": 22, "theme": "Roblox", "text": "En 'Tower of Hell' subes 7 pisos y cada piso tiene 15 escalones. ¿Cuántos escalones subiste en total?", "answer": "105", "reward": "oof_sound", "operation_type": "Multiplicación"},
            {"id": 23, "theme": "Roblox", "text": "Tienes 64 bloques y quieres hacer torres de 8 bloques cada una. ¿Cuántas torres podrás construir?", "answer": "8", "reward": "oof_sound", "operation_type": "División"},
            {"id": 24, "theme": "Roblox", "text": "Si 3 espadas cuestan 270 Robux en total, ¿cuánto cuesta cada una?", "answer": "90", "reward": "oof_sound", "operation_type": "División"},
            {"id": 25, "theme": "Roblox", "text": "En 'Brookhaven' una casa cuesta 750 bucks. Si ya tienes 500, ¿cuánto más necesitas?", "answer": "250", "reward": "oof_sound", "operation_type": "Resta"},
            {"id": 26, "theme": "Roblox", "text": "Un huevo de mascota cuesta 600 bucks. Si compras 2, ¿cuánto pagas en total?", "answer": "1200", "reward": "oof_sound", "operation_type": "Multiplicación"},
            {"id": 27, "theme": "Roblox", "text": "Un coche cuesta 900 Robux. Si ya tienes 1,200, ¿cuánto te sobra después de comprarlo?", "answer": "300", "reward": "oof_sound", "operation_type": "Resta"},
            {"id": 28, "theme": "Roblox", "text": "Un evento reparte 240 monedas entre 12 jugadores. ¿Cuántas recibe cada uno?", "answer": "20", "reward": "oof_sound", "operation_type": "División"},
            {"id": 29, "theme": "Roblox", "text": "Tienes 2 mascotas. Una cuesta 300 y otra 450 bucks. ¿Cuánto gastaste en total?", "answer": "750", "reward": "oof_sound", "operation_type": "Suma"},
            {"id": 30, "theme": "Roblox", "text": "En una carrera avanzas 60 metros. Otro jugador avanza 45. ¿Cuántos metros más avanzaste?", "answer": "15", "reward": "oof_sound", "operation_type": "Resta"},
            {"id": 31, "theme": "Roblox", "text": "Si cada caja trae 12 pociones y compras 4 cajas, ¿cuántas pociones tienes?", "answer": "48", "reward": "oof_sound", "operation_type": "Multiplicación"},
            {"id": 32, "theme": "Roblox", "text": "Una mascota se alimenta con 3 galletas al día. ¿Cuántas galletas necesitará en 7 días?", "answer": "21", "reward": "oof_sound", "operation_type": "Multiplicación"},
            {"id": 33, "theme": "Roblox", "text": "Si tienes 500 Robux y gastas 3/5 en ropa, ¿cuántos Robux gastaste?", "answer": "300", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 34, "theme": "Roblox", "text": "De 120 bloques usaste 1/4 para hacer una base. ¿Cuántos bloques usaste?", "answer": "30", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 35, "theme": "Roblox", "text": "Si ganas 2/3 de 90 monedas en un reto, ¿cuántas monedas ganas?", "answer": "60", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 36, "theme": "Roblox", "text": "Un jugador tiene 150 Robux y gasta 2/5 en pociones. ¿Cuánto gasta?", "answer": "60", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 37, "theme": "Roblox", "text": "Si recoges 3/10 de 200 bloques, ¿cuántos bloques recogiste?", "answer": "60", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 38, "theme": "Roblox", "text": "En un obby superas 80 obstáculos. Si completas 3/4, ¿cuántos obstáculos pasaste?", "answer": "60", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 39, "theme": "Roblox", "text": "Tienes 5/8 de 64 Robux. ¿Cuántos Robux son?", "answer": "40", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 40, "theme": "Roblox", "text": "Si un escudo cuesta 2/3 de 90 Robux, ¿cuánto cuesta?", "answer": "60", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 41, "theme": "Roblox", "text": "En un servidor hay 48 jugadores. Si 1/2 son de tu equipo, ¿cuántos jugadores tienes en tu equipo?", "answer": "24", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 42, "theme": "Roblox", "text": "Si gastas 1/5 de 200 Robux en decoraciones, ¿cuánto gastaste?", "answer": "40", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 43, "theme": "Roblox", "text": "De 300 monedas, usas 3/10 para comprar comida. ¿Cuántas monedas gastas?", "answer": "90", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 44, "theme": "Roblox", "text": "Tienes 100 bloques. Usas 7/10 en una torre. ¿Cuántos bloques usaste?", "answer": "70", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 45, "theme": "Roblox", "text": "De 72 Robux, gastas 3/4 en un arma. ¿Cuánto gastaste?", "answer": "54", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 46, "theme": "Roblox", "text": "Si ganas 5/6 de 120 puntos en un reto, ¿cuántos puntos ganas?", "answer": "100", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 47, "theme": "Roblox", "text": "Si completas 2/5 de 150 plataformas, ¿cuántas pasaste?", "answer": "60", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 48, "theme": "Roblox", "text": "Un evento da 3/4 de 80 monedas a cada jugador. ¿Cuántas monedas son?", "answer": "60", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 49, "theme": "Roblox", "text": "Tienes 2/3 de 90 Robux guardados. ¿Cuánto es eso?", "answer": "60", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 50, "theme": "Roblox", "text": "Si una mascota cuesta 5/10 de 200 bucks, ¿cuánto cuesta?", "answer": "100", "reward": "oof_sound", "operation_type": "Fracción"},
            {"id": 51, "theme": "Roblox", "text": "En un 'Tycoon', tu base genera 20 monedas por minuto. ¿Cuántas monedas tendrás después de 15 minutos?", "answer": "300", "operation_type": "Multiplicación"},
            {"id": 52, "theme": "Roblox", "text": "Un servidor de 'Arsenal' tiene 16 jugadores. Si se dividen en 4 equipos iguales, ¿cuántos jugadores hay por equipo?", "answer": "4", "operation_type": "División"},
            {"id": 53, "theme": "Roblox", "text": "Tienes 850 Robux. Si compras un accesorio de 320 y una animación de 250, ¿cuántos Robux te quedan?", "answer": "280", "operation_type": "Resta"},
            {"id": 54, "theme": "Roblox", "text": "En 'Jailbreak', escapas de la prisión 5 veces en un día. Si cada escape te da 150 de dinero, ¿cuánto ganaste?", "answer": "750", "operation_type": "Multiplicación"},
            {"id": 55, "theme": "Roblox", "text": "Un jefe en 'Dungeon Quest' tiene 5000 de vida. Si tu equipo le quita 1250 de vida, ¿cuánta vida le queda?", "answer": "3750", "operation_type": "Resta"},
            {"id": 56, "theme": "Roblox", "text": "En 'Bloxy Bingo', completas una tarjeta y ganas 80 tickets. Si ya tenías 125, ¿cuántos tienes ahora?", "answer": "205", "operation_type": "Suma"},
            {"id": 57, "theme": "Roblox", "text": "Una carrera en 'Vehicle Simulator' dura 3 minutos. ¿Cuántos segundos son eso?", "answer": "180", "operation_type": "Multiplicación"},
            {"id": 58, "theme": "Roblox", "text": "Completas 2/3 de un obby de 90 etapas. ¿Cuántas etapas completaste?", "answer": "60", "operation_type": "Fracción"},
            {"id": 59, "theme": "Roblox", "text": "Hay 120 jugadores en un evento. Si 3/4 de ellos usan un sombrero especial, ¿cuántos jugadores son?", "answer": "90", "operation_type": "Fracción"},
            {"id": 60, "theme": "Roblox", "text": "En 'Work at a Pizza Place', entregas 14 pizzas. Si cada entrega te da 20 monedas, ¿cuántas ganas?", "answer": "280", "operation_type": "Multiplicación"},
            {"id": 61, "theme": "Roblox", "text": "Tienes 45 amigos en Roblox y 18 están conectados. ¿Cuántos no están conectados?", "answer": "27", "operation_type": "Resta"},
            {"id": 62, "theme": "Roblox", "text": "Un pack de 10 pociones cuesta 250 Robux. ¿Cuánto cuesta cada poción?", "answer": "25", "operation_type": "División"},
            {"id": 63, "theme": "Roblox", "text": "Ganas 320 puntos en un minijuego y 450 en otro. ¿Cuántos puntos tienes en total?", "answer": "770", "operation_type": "Suma"},
            {"id": 64, "theme": "Roblox", "text": "En 'Murder Mystery 2', encuentras 15 monedas en una ronda. ¿Cuántas rondas necesitas para juntar 75 monedas?", "answer": "5", "operation_type": "División"},
            {"id": 65, "theme": "Roblox", "text": "Una casa en 'Brookhaven' cuesta 800. Si tienes 1/2 del dinero, ¿cuánto dinero tienes?", "answer": "400", "operation_type": "Fracción"},
            {"id": 66, "theme": "Roblox", "text": "Si 6 jugadores se reparten 480 Robux de un premio, ¿cuánto recibe cada uno?", "answer": "80", "operation_type": "División"},
            {"id": 67, "theme": "Roblox", "text": "Tu personaje salta 12 studs de alto. Un muro mide 36 studs. ¿Cuántos saltos necesitas para llegar a la cima?", "answer": "3", "operation_type": "División"},
            {"id": 68, "theme": "Roblox", "text": "Un evento especial dura 240 minutos. ¿Cuántas horas son?", "answer": "4", "operation_type": "División"},
            {"id": 69, "theme": "Roblox", "text": "Tienes 900 bucks y gastas 430 en un coche. ¿Cuántos bucks te quedan?", "answer": "470", "operation_type": "Resta"},
            {"id": 70, "theme": "Roblox", "text": "En 'Piggy', necesitas encontrar 8 llaves. Si ya encontraste 5, ¿cuántas te faltan?", "answer": "3", "operation_type": "Resta"},
            {"id": 71, "theme": "Roblox", "text": "Un teletransportador te lleva 500 studs. Si lo usas 3 veces, ¿qué distancia total recorriste?", "answer": "1500", "operation_type": "Multiplicación"},
            {"id": 72, "theme": "Roblox", "text": "Si una mascota legendaria aparece 1 de cada 1000 huevos, ¿qué probabilidad en fracción tienes de conseguirla?", "answer": "1/1000", "operation_type": "Fracción"},
            {"id": 73, "theme": "Roblox", "text": "En 'Adopt Me!', intercambias 4 mascotas comunes por 1 rara. Si tienes 24 comunes, ¿cuántas raras puedes obtener?", "answer": "6", "operation_type": "División"},
            {"id": 74, "theme": "Roblox", "text": "Tienes 150 amigos y 2/3 son de México. ¿Cuántos amigos mexicanos tienes?", "answer": "100", "operation_type": "Fracción"},
            {"id": 75, "theme": "Roblox", "text": "Un jetpack cuesta 2500 Robux. Si tienes 1850, ¿cuántos te faltan?", "answer": "650", "operation_type": "Resta"},
            {"id": 76, "theme": "Minecraft", "text": "Para hacer una espada de diamante necesitas 2 diamantes. Si encuentras 14 diamantes, ¿cuántas espadas puedes hacer?", "answer": "7", "operation_type": "División"},
            {"id": 77, "theme": "Minecraft", "text": "Tienes 3 stacks de 64 bloques de adoquín. ¿Cuántos bloques tienes en total?", "answer": "192", "operation_type": "Multiplicación"},
            {"id": 78, "theme": "Minecraft", "text": "Un Creeper te quita 4 corazones de vida. Si tienes 10, ¿cuántos te quedan?", "answer": "6", "operation_type": "Resta"},
            {"id": 79, "theme": "Minecraft", "text": "Encuentras 8 lingotes de oro en un cofre y 12 en otro. ¿Cuántos lingotes de oro tienes?", "answer": "20", "operation_type": "Suma"},
            {"id": 80, "theme": "Minecraft", "text": "Para hacer un pastel necesitas 3 de trigo. Si tu granja produce 21 de trigo, ¿cuántos pasteles puedes hacer?", "answer": "7", "operation_type": "División"},
            {"id": 81, "theme": "Minecraft", "text": "Un esqueleto te dispara 5 flechas. Si tenías 32, ¿cuántas flechas te quedan?", "answer": "27", "operation_type": "Resta"},
            {"id": 82, "theme": "Minecraft", "text": "Si 1 lingote de oro se convierte en 9 pepitas, ¿cuántas pepitas obtienes de 7 lingotes?", "answer": "63", "operation_type": "Multiplicación"},
            {"id": 83, "theme": "Minecraft", "text": "Necesitas 15 librerías para tu mesa de encantamientos. Si ya tienes 8, ¿cuántas te faltan?", "answer": "7", "operation_type": "Resta"},
            {"id": 84, "theme": "Minecraft", "text": "De 40 chuletas de cerdo, cocinas 3/5. ¿Cuántas chuletas cocinaste?", "answer": "24", "operation_type": "Fracción"},
            {"id": 85, "theme": "Minecraft", "text": "Un golem de nieve se construye con 2 bloques de nieve. Si tienes 28 bloques, ¿cuántos golems puedes hacer?", "answer": "14", "operation_type": "División"},
            {"id": 86, "theme": "Minecraft", "text": "Un aldeano te vende 1 esmeralda por 24 de papel. Si le das 72 de papel, ¿cuántas esmeraldas te da?", "answer": "3", "operation_type": "División"},
            {"id": 87, "theme": "Minecraft", "text": "Tu pico de hierro tiene 250 de durabilidad. Cada bloque que picas le quita 1. Si picas 120 bloques, ¿cuánta durabilidad le queda?", "answer": "130", "operation_type": "Resta"},
            {"id": 88, "theme": "Minecraft", "text": "Un portal al Nether necesita 10 de obsidiana. Si tienes 3 portales, ¿cuánta obsidiana usaste?", "answer": "30", "operation_type": "Multiplicación"},
            {"id": 89, "theme": "Minecraft", "text": "Encuentras un tesoro con 5 diamantes, 12 de oro y 20 de hierro. ¿Cuántos minerales valiosos encontraste en total?", "answer": "37", "operation_type": "Suma"},
            {"id": 90, "theme": "Minecraft", "text": "Tienes 18 perlas de Ender. Si usas 12 para encontrar el portal al End, ¿cuántas te quedan?", "answer": "6", "operation_type": "Resta"},
            {"id": 91, "theme": "Minecraft", "text": "Un stack de huevos contiene 16 huevos. Si tienes 4 stacks, ¿cuántos huevos tienes?", "answer": "64", "operation_type": "Multiplicación"},
            {"id": 92, "theme": "Minecraft", "text": "De 30 semillas, plantas 2/3 en tu huerto. ¿Cuántas semillas plantaste?", "answer": "20", "operation_type": "Fracción"},
            {"id": 93, "theme": "Minecraft", "text": "Para un faro (beacon) necesitas 1 estrella del Nether. Si matas a 3 Withers, ¿cuántos faros puedes hacer?", "answer": "3", "operation_type": "Multiplicación"},
            {"id": 94, "theme": "Minecraft", "text": "Un cofre puede almacenar 27 stacks de objetos. Si tienes 3 cofres, ¿cuántos stacks puedes guardar?", "answer": "81", "operation_type": "Multiplicación"},
            {"id": 95, "theme": "Minecraft", "text": "Una manzana dorada te cura 4 corazones. Si estás a 2 corazones y te comes una, ¿cuántos corazones tendrás?", "answer": "6", "operation_type": "Suma"},
            {"id": 96, "theme": "Minecraft", "text": "Tienes 50 bloques de cristal. Si usas 35 para hacer ventanas, ¿cuántos te sobran?", "answer": "15", "operation_type": "Resta"},
            {"id": 97, "theme": "Minecraft", "text": "Un shulker te dispara y te hace flotar por 10 segundos. Si te dispara 4 veces, ¿cuánto tiempo flotas en total?", "answer": "40", "operation_type": "Multiplicación"},
            {"id": 98, "theme": "Minecraft", "text": "Un aldeano zombi tarda 4 minutos en curarse. ¿Cuántos segundos son?", "answer": "240", "operation_type": "Multiplicación"},
            {"id": 99, "theme": "Minecraft", "text": "Encuentras 128 bloques de arena. Si los usas todos para hacer cristal (1 a 1), ¿cuánto cristal obtienes?", "answer": "128", "operation_type": "Suma"},
            {"id": 100, "theme": "Minecraft", "text": "De 25 diamantes, usas 1/5 para hacer una pala. ¿Cuántos diamantes usaste?", "answer": "5", "operation_type": "Fracción"},
            {"id": 101, "theme": "FNAF", "text": "El guardia debe vigilar 8 cámaras y 3 conductos. ¿Cuántos puntos debe revisar en total?", "answer": "11", "reward": "fnaf_sound", "operation_type": "Suma"},
            {"id": 102, "theme": "FNAF", "text": "Empiezas con 100% de batería. Si Foxy te quita 15% al golpear la puerta, ¿cuánta batería te queda?", "answer": "85", "reward": "fnaf_sound", "operation_type": "Resta"},
            {"id": 103, "theme": "FNAF", "text": "Freddy, Bonnie y Chica están en el escenario. Si cada uno tiene 2 ojos, ¿cuántos ojos ves en total?", "answer": "6", "reward": "fnaf_sound", "operation_type": "Multiplicación"},
            {"id": 104, "theme": "FNAF", "text": "Hay 24 cupcakes en la cocina. Si Chica los reparte entre 6 niños, ¿cuántos le tocan a cada uno?", "answer": "4", "reward": "fnaf_sound", "operation_type": "División"},
            {"id": 105, "theme": "FNAF", "text": "Bonnie se movió 7 veces en la primera hora y 9 en la segunda. ¿Cuántas veces se ha movido?", "answer": "16", "reward": "fnaf_sound", "operation_type": "Suma"},
            {"id": 106, "theme": "FNAF", "text": "Necesitas 20 Faz-Coins para un peluche. Si ya tienes 12, ¿cuántas te faltan?", "answer": "8", "reward": "fnaf_sound", "operation_type": "Resta"},
            {"id": 107, "theme": "FNAF", "text": "El show principal dura 5 minutos. Si se repite 8 veces al día, ¿cuántos minutos de show hay en total?", "answer": "40", "reward": "fnaf_sound", "operation_type": "Multiplicación"},
            {"id": 108, "theme": "FNAF", "text": "El generador tiene 60 unidades de energía. Si gastas 10 por hora, ¿para cuántas horas te alcanza?", "answer": "6", "reward": "fnaf_sound", "operation_type": "División"},
            {"id": 109, "theme": "FNAF", "text": "De las 12 cámaras, 1/3 muestran pasillos oscuros. ¿Cuántas cámaras son?", "answer": "4", "reward": "fnaf_sound", "operation_type": "Fracción"},
            {"id": 110, "theme": "FNAF", "text": "Hay 10 niños en la pizzería. Si 4 se esconden, ¿cuántos quedan a la vista?", "answer": "6", "reward": "fnaf_sound", "operation_type": "Resta"},
            {"id": 111, "theme": "FNAF", "text": "Cada animatrónico tiene 5 dedos en una mano. ¿Cuántos dedos tienen las 2 manos de Foxy juntas?", "answer": "10", "reward": "fnaf_sound", "operation_type": "Multiplicación"},
            {"id": 112, "theme": "FNAF", "text": "En la sala de repuestos hay 3 cabezas y 5 cuerpos. ¿Cuántas partes de animatrónicos hay?", "answer": "8", "reward": "fnaf_sound", "operation_type": "Suma"},
            {"id": 113, "theme": "FNAF", "text": "Tienes 30 segundos para reiniciar la ventilación. Si el proceso tiene 5 pasos, ¿cuántos segundos tienes por paso?", "answer": "6", "reward": "fnaf_sound", "operation_type": "División"},
            {"id": 114, "theme": "FNAF", "text": "La música de Puppet dura 60 segundos. Si ya pasaron 45, ¿cuántos segundos quedan antes de que salga?", "answer": "15", "reward": "fnaf_sound", "operation_type": "Resta"},
            {"id": 115, "theme": "FNAF", "text": "Tienes 8 porciones de pizza. Si te comes 1/4, ¿cuántas porciones te comiste?", "answer": "2", "reward": "fnaf_sound", "operation_type": "Fracción"}
        ]

    def get_random_mission(self):
        """Devuelve una misión aleatoria de la lista."""
        return random.choice(self.missions)

